### ISSUE TITLE
Add support for pull requests

### ISSUE THREAD

**Issue by choldgraf** [docathon/watchtower#15]
Right now we are storing commits / issues, but not pull requests. Would be useful to do so in order to track something like avg. amount of time to close for pull requests:

https://developer.github.com/v3/pulls/#list-pull-requests

**Comment by NelleV** [comment]
pull request are just issues with a pr tag, so we do store them.

**Comment by choldgraf** [comment]
no way, really?! that's cool!

in that case, maybe it's worth dealing with on the handler side? E.g. the handler would separate the two? I think that's how users will conceptualize this
